# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0.xci
# IP: The module: 'dijkstra_hw_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_hw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_hw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_hw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0.xci
# IP: The module: 'dijkstra_hw_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_hw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_hw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_hw_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
