# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_auto_pc_0/dijkstra_hw_auto_pc_0.xci
# IP: The module: 'dijkstra_hw_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_auto_pc_0/dijkstra_hw_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_hw_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_auto_pc_0/dijkstra_hw_auto_pc_0.xci
# IP: The module: 'dijkstra_hw_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_auto_pc_0/dijkstra_hw_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dijkstra_hw_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
