# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.cache/wt [current_project]
set_property parent.project_path /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/ip_repo [current_project]
set_property ip_output_repo /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/hdl/dijkstra_hw_wrapper.vhd
add_files /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/dijkstra_hw.bd
set_property used_in_implementation false [get_files -all /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_processing_system7_0_0/dijkstra_hw_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/ip/dijkstra_hw_auto_pc_0/dijkstra_hw_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/dijkstra_hw_ooc.xdc]
set_property is_locked true [get_files /mnt/windows/Users/ricky/Seafile/Library/School/F17/EEL4720/prj/dijkstra_fpga/src/hw/dijkstra_fpga/dijkstra_fpga.srcs/sources_1/bd/dijkstra_hw/dijkstra_hw.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dijkstra_hw_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef dijkstra_hw_wrapper.dcp

catch { report_utilization -file dijkstra_hw_wrapper_utilization_synth.rpt -pb dijkstra_hw_wrapper_utilization_synth.pb }
