# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dijkstra_hw/dijkstra_hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dijkstra_hw || ORIG_REF_NAME==dijkstra_hw}]

# IP: bd/dijkstra_hw/ip/dijkstra_hw_processing_system7_0_0/dijkstra_hw_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dijkstra_hw_processing_system7_0_0 || ORIG_REF_NAME==dijkstra_hw_processing_system7_0_0}]

# IP: bd/dijkstra_hw/ip/dijkstra_hw_accelerator_0_0/dijkstra_hw_accelerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dijkstra_hw_accelerator_0_0 || ORIG_REF_NAME==dijkstra_hw_accelerator_0_0}]

# IP: bd/dijkstra_hw/ip/dijkstra_hw_ps7_0_axi_periph_0/dijkstra_hw_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dijkstra_hw_ps7_0_axi_periph_0 || ORIG_REF_NAME==dijkstra_hw_ps7_0_axi_periph_0}]

# IP: bd/dijkstra_hw/ip/dijkstra_hw_rst_ps7_0_100M_0/dijkstra_hw_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dijkstra_hw_rst_ps7_0_100M_0 || ORIG_REF_NAME==dijkstra_hw_rst_ps7_0_100M_0}]

# IP: bd/dijkstra_hw/ip/dijkstra_hw_auto_pc_0/dijkstra_hw_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dijkstra_hw_auto_pc_0 || ORIG_REF_NAME==dijkstra_hw_auto_pc_0}]

# XDC: bd/dijkstra_hw/dijkstra_hw_ooc.xdc
